######################################################################
# - ADAM - SPACE AT IN EDGE OF ADAM - FROM HEAVEN TO HELL -
######################################################################
FROM heaven:latest
# ######################################################################
RUN mkdir -p /anubis/src/adam && cd /anubis/src/adam && git clone https://github.com/lf-edge/adam .
# ######################################################################
RUN ls -la /anubis/src/adam/

