######################################################################
# - EVE - ALL WHAT ARE HAVE BORN - LIVE AT EDGE ON HELL -
######################################################################
FROM heaven:latest

RUN mkdir -p /anubis/src/eve && cd /anubis/src/eve && git clone https://github.com/lf-edge/eve .
RUN cd /anubis/src/eve/ && ./eve/tools/makeconfig.sh
# RUN ls -la /anubis/src/eve/ && cd tools && bash -c './*.sh'
# RUN ls -la /anubis/src/eve/ && make live
######################################################################
