FROM alpine:edge
# EDEN 4 ADAM'S WITH EVE'S AT EDGE 

RUN apk update && apk add alpine-conf
RUN setup-apkrepos -d && apk update && apk upgrade
RUN apk add git make busybox-extras squashfs-tools qemu-img qemu-system-x86_64 go docker-cli

RUN mkdir -p /_vx_edge
WORKDIR /_vx_edge/
COPY ./_vx_edge/. /_vx_edge/
RUN ls -la /_vx_edge/

RUN mkdir -p /opt/eden-edge-sync
RUN mkdir -p /opt/src && mkdir /opt/eden

WORKDIR /opt/src

RUN cd /opt/src && git clone 